### ISSUE TITLE
Better support for BLE beacons

### ISSUE THREAD

**Issue by miek** [mwylde/rumble#19]
I've been trying to use Rumble to pull in data from BLE beacons but I'm running into some issues where the API doesn't seem suited for them. Beacons are BLE devices that don't have any way to form a connection, instead they just embed data in advertising packets.

One issue is that Rumble ignores duplicates when scanning. This could be made optional depending on the use case.

The other issue was handling events. I tried using `Central::on_event`, which works, but I couldn't see a nice way to get at the `central` data in the main thread from the event context.
I've ended up just polling `central.peripherals()` from my main thread for now, but it's not a great solution: https://github.com/miek/ruuvi-collector-rs/blob/master/src/main.rs#L109

**Comment by lautis** [comment]
I have a very similar project where I use `Central::on_event` to listen to the individual events (https://github.com/lautis/ruuvitag-listener/blob/master/src/ruuvi.rs#L35) and pass the parsed events forward to the main function in a callback function https://github.com/lautis/ruuvitag-listener/blob/master/src/main.rs#L145. The callback is executed in another thread as I'm not using channels.

That said, I still seem to get only one update message per scan, so I have to restart scanning every 2 seconds.

**Comment by lautis** [comment]
For the ruuvitag use case, it would be nicer to use passive scanning (https://github.com/mwylde/rumble/blob/master/src/bluez/adapter/mod.rs#L377) and have duplicates filter disabled (https://github.com/mwylde/rumble/blob/master/src/bluez/adapter/mod.rs#L389)
