### ISSUE TITLE
char-read functionality

### ISSUE THREAD

**Issue by MrSpock** [mwylde/rumble#21]
Is there a way to achive equivalent of:
`gatttool --device=MAC--char-read -a 0x18`
Docs show only read_by_type which is different request type.
Below is wireshark pcap of above query by gattool.
<img width="558" alt="screenshot 2018-12-19 21 26 10" src="https://user-images.githubusercontent.com/681680/50246483-d223f500-03d5-11e9-8d69-49ca654faae9.png">

read_by_type is:
<img width="414" alt="screenshot 2018-12-19 21 34 43" src="https://user-images.githubusercontent.com/681680/50246543-f54ea480-03d5-11e9-8ecf-ef3d39c537ed.png">

Result is I'm getting wrong response..

**Comment by jmagnuson** [comment]
I needed that functionality as well, and implemented in a branch here:
https://github.com/jmagnuson/rumble/commit/c63e0a0e2242b16fa5f861076acf42cf85eb8279

I don't know if `Peripheral` should be the place for all GATT stuff long term-- would be awesome to see a `Gatt` trait but I haven't had time to work on that.

**Comment by MrSpock** [comment]
Any plans to merge with "stable" release ?
