### ISSUE TITLE
module `peripheral` is private

### ISSUE THREAD

**Issue by osynge** [mwylde/rumble#34]
After expanding beyond the basic example I wanted to pass the Peripheral to a function to act on it. Sadly whenever I put "rumble::bluez::adapter::peripheral::Peripheral" in the parameters I get the following error:

    error[E0603]: module `peripheral` is private

**Comment by mwylde** [comment]
Thanks for checking out rumble! The reason Peripheral is private is because it's intended as an implementation detail of the bluez (linux) implementation. Instead, try using the `rumble::api::Peripheral` trait.

For example:

```rust
use rumble::api::Peripheral;

fn handle_peripheral<P: Peripheral + 'static>(peripheral: P) {
...
}
```

**Comment by osynge** [comment]
Thankyou this explains the issue, but please see thread https://github.com/mwylde/rumble/issues/7 for clarification.
