### ISSUE TITLE
Accessing adapter without elevated privileges

### ISSUE THREAD

**Issue by felsweg** [mwylde/rumble#40]
Right now, accessing any adapter requires elevated privileges (eg. root). Is it possible to use an adapter without requiring elevated privileges? if yes, how would I do that? Thank you.

**Comment by lihop** [comment]
I found that it is possible to use this library without root privileges by setting the `cap_net_raw` and `cap_net_admin+eip` capabilities on the output binary as outlined in this [Stack Exchange answer](https://unix.stackexchange.com/a/182559).

So, in the lights example,
```
$ cargo build --release --example lights
...
$ sudo setcap 'cap_net_raw,cap_net_admin+eip' target/release/examples/lights
```
allows me to run the lights binary without root.

**Comment by felsweg** [comment]
looks like, that this is the best solution. thanks.
